import type { Metadata } from "next";
import Link from "next/link";
import LegalPage from "@/components/legal/legal-page";
import { ORG, formattedAddress } from "@/lib/legal/org";

export const metadata: Metadata = {
  title: "Privacy Policy - Newah Organization of America",
  description:
    "How the Northern California Chapter of the Newah Organization of America collects, uses, shares and protects the information you provide.",
};

export default function PrivacyPage() {
  return (
    <LegalPage title="Privacy Policy">
      <p>
        This Privacy Policy explains how {ORG.name} (&ldquo;{ORG.shortName}
        &rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;), acting through its {ORG.chapter},
        collects, uses, shares and protects information you give us through this
        website. Please read it together with our{" "}
        <Link href="/terms">Terms and Conditions</Link>.
      </p>
      <p>
        By submitting a registration or donation form on this site, you confirm you
        have read this policy and consent to the uses described in it.
      </p>

      <h2>1. Information we collect</h2>
      <p>We collect only what you type into our forms. Specifically:</p>
      <ul>
        <li><strong>Your name</strong>, as entered on the registration form.</li>
        <li><strong>Your email address.</strong></li>
        <li><strong>Your telephone number.</strong></li>
        <li>
          <strong>The name and email address of each additional adult</strong> attending with
          you, so we can prepare their name tag.
        </li>
        <li><strong>Whether you brought food</strong>, and what you brought.</li>
        <li><strong>Donation amount</strong>, and whether you chose to cover the card processing fee.</li>
        <li>
          <strong>A record of your consent</strong> &mdash; the exact wording you agreed
          to, the version of that wording, and the date and time you agreed.
        </li>
        <li>
          <strong>A registration reference code</strong> and the date and time of your
          submission, generated by us.
        </li>
      </ul>
      <p>
        We do not use advertising trackers, we do not run analytics that profile you
        across other websites, and we do not buy information about you from anyone.
      </p>
      <h3>Payment information</h3>
      <p>
        If you make a donation, your card details are entered on a payment page hosted
        by our payment processor and are handled entirely by that processor.{" "}
        <strong>We never see, receive or store your card number.</strong> We receive
        only a confirmation of whether the payment succeeded, and the amount.
      </p>

      <h2>2. How we use your information</h2>
      <p>
        We use the information you provide to operate the organization and to stay in
        touch with our community. Specifically, we use it to:
      </p>
      <ul>
        <li>process and confirm your event registration or donation;</li>
        <li>send you a confirmation and, where relevant, a receipt;</li>
        <li>contact you about the event you registered for, including changes to it;</li>
        <li><strong>reach out to you with requests for support</strong> for the organization and its activities;</li>
        <li><strong>contact you about membership drives</strong> and invite you to become or renew as a member;</li>
        <li><strong>tell you about upcoming and future events</strong> organized by {ORG.shortName} and its Northern California Chapter;</li>
        <li><strong>send you other communications from the organization</strong>, such as community news and announcements;</li>
        <li>plan catering, seating and logistics, using guest counts and food selections;</li>
        <li>keep accurate financial and membership records, and meet our legal and tax obligations.</li>
      </ul>
      <p>
        You consent to these uses when you tick the consent box on our forms.{" "}
        <strong>You can withdraw that consent at any time</strong> by emailing us at{" "}
        <a href={`mailto:${ORG.contactEmail}`}>{ORG.contactEmail}</a>. Withdrawing
        consent stops future communications; it does not undo anything already done, and
        we may still contact you about a registration or donation you have already made.
      </p>

      <h2>3. We do not sell your information</h2>
      <p>
        <strong>
          We do not sell, rent, trade or share your personal information with third
          parties for their own marketing purposes.
        </strong>{" "}
        We have never done so and this policy does not permit it.
      </p>

      <h2>4. Who we share it with</h2>
      <p>
        We share information only with the service providers that make this website work,
        and only to the extent they need it to provide their service to us:
      </p>
      <ul>
        <li><strong>Supabase</strong> &mdash; hosts the database that stores registrations.</li>
        <li><strong>Vercel</strong> &mdash; hosts this website and serves its pages.</li>
        <li><strong>Resend</strong> &mdash; sends confirmation emails on our behalf.</li>
        <li><strong>Stripe</strong> &mdash; processes donation payments.</li>
      </ul>
      <p>
        These providers are bound by their own agreements with us and are not permitted
        to use your information for their own purposes.
      </p>
      <p>
        We may also disclose information where we are legally required to &mdash; for
        example in response to a valid subpoena, court order or lawful government request
        &mdash; or where we reasonably believe disclosure is necessary to protect the
        rights, safety or property of the organization, our members or the public.
      </p>

      <h2>5. Your choices and your rights</h2>
      <p>You may, at any time:</p>
      <ul>
        <li><strong>Ask what we hold</strong> about you, and receive a copy.</li>
        <li><strong>Ask us to correct</strong> anything inaccurate.</li>
        <li><strong>Ask us to delete</strong> your information, subject to records we must keep for financial or legal reasons.</li>
        <li><strong>Withdraw your consent</strong> to being contacted, or unsubscribe from any email we send you.</li>
      </ul>
      <p>
        To exercise any of these, email{" "}
        <a href={`mailto:${ORG.contactEmail}`}>{ORG.contactEmail}</a>. We will respond
        within 45 days. We will never treat you differently, or deny you participation in
        an event, because you exercised one of these choices.
      </p>
      <p>
        Nonprofit organizations are generally outside the scope of the California Consumer
        Privacy Act. We nonetheless extend the rights above to everyone who uses this site,
        as a matter of practice rather than because we are compelled to.
      </p>

      <h2>6. How long we keep it</h2>
      <p>
        We keep registration records for as long as needed for the event and for our
        ongoing community and membership records. Financial records relating to donations
        are kept for at least seven years, as required for tax and accounting purposes.
        When information is no longer needed, we delete it or render it anonymous.
      </p>

      <h2>7. How we protect it</h2>
      <p>
        Information is stored in a managed database with access restricted to authorized
        members of the board. The site is served over encrypted connections (HTTPS), and
        the administrative view that lists registrations is password protected. No method
        of storage or transmission over the internet is completely secure, and we cannot
        guarantee absolute security; we will notify affected people promptly if a breach
        occurs that is likely to put them at risk.
      </p>

      <h2>8. Children</h2>
      <p>
        <strong>We do not collect any personal information about anyone under 18.</strong> The
        registration form asks only for the names and email addresses of attending adults, and
        it says so. Children are welcome at our events and need not be named here; a name tag
        can be written for them at the registration desk.
      </p>
      <p>
        If you believe details of a child have been submitted to us anyway, email us and we
        will delete them.
      </p>

      <h2>9. Changes to this policy</h2>
      <p>
        We may update this policy. The effective date at the top of this page shows when
        it last changed. Where a change materially affects how we use information you
        already gave us, we will seek your consent again rather than rely on the old one.
      </p>

      <h2>10. Contact us</h2>
      <p>
        Questions, requests or complaints about this policy, or about how your information
        has been handled, should go to:
      </p>
      <p>
        <strong>{ORG.legalName}</strong>
        <br />
        {ORG.chapter}
        <br />
        Email: <a href={`mailto:${ORG.contactEmail}`}>{ORG.contactEmail}</a>
        <br />
        {formattedAddress()}
      </p>
    </LegalPage>
  );
}
